### ISSUE TITLE
Database / Call to a member function recordQueryCompletion() on null

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticWatchlist#71]
[0], best to avoid `MW-master` / MW 1.28 as test instance.

```
Using PHP 7.0.13

Semantic Watchlist: 1.2.0-alpha

Semantic MediaWiki: 2.5.0-alpha (SMWSQLStore3, mysql)
MediaWiki:          1.29.0-alpha (MediaWiki vendor autoloader)
Site language:      en

Execution time:     2016-11-24 08:04
Xdebug:             2.4.1 (enabled)

PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticWatchlist/phpunit.xml.dist

...............................................................  63 / 100 ( 63%)
...................................[dad17321a2e258f6c919713d] [no req]   Error from line 957 of /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php: Call to a member function recordQueryCompletion() on null
Backtrace:
#0 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(870): Database->doProfiledQuery(string, string, boolean, string)
#1 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(2734): Database->query(string, string)
#2 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(2704): Database->doBegin(string)
#3 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(2639): Database->begin(string, string)
#4 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticWatchlist/src/TableUpdater.php(40): Database->startAtomic(string)
#5 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticWatchlist/tests/phpunit/Unit/TableUpdaterTest.php(58): SWL\TableUpdater->updateGroupIdsForUser(integer, array)
#6 [internal function]: SWL\Tests\TableUpdaterTest->testUpdateGroupIdsForUserToReplaceDatasetByUserId()
#7 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(987): ReflectionMethod->invokeArgs(SWL\Tests\TableUpdaterTest, array)
#8 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(838): PHPUnit_Framework_TestCase->runTest()
#9 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#10 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(783): PHPUnit_Framework_TestResult->run(SWL\Tests\TableUpdaterTest)
#11 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php(779): PHPUnit_Framework_TestCase->run(PHPUnit_Framework_TestResult)
#12 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php(749): PHPUnit_Framework_TestSuite->runTest(SWL\Tests\TableUpdaterTest, PHPUnit_Framework_TestResult)
#13 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php(707): PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult, boolean, array, array, boolean)
#14 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult, boolean, array, array, boolean)
#15 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(PHPUnit_Framework_TestSuite, array)
#16 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php(129): PHPUnit_TextUI_Command->run(array, boolean)
#17 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(133): PHPUnit_TextUI_Command::main()
#18 /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php(111): PHPUnitMaintClass->execute()
#19 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(163): require(string)
#20 {main}
```

[0] https://travis-ci.org/SemanticMediaWiki/SemanticWatchlist/jobs/178520211

**Comment by mwjames** [comment]
https://phabricator.wikimedia.org/T170030

**Comment by labster** [comment]
Fixed by replacing the unit test with a integration test in #118
